# Generated by Django 4.2.9 on 2024-02-10 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_comentario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['-publicado_em']},
        ),
    ]
